name: build-deploy

on:
  push:
    branches: main

jobs:
  use-build:
    uses: bharat5604/portfolio/.github/workflows/build.yml@main

  deploy:
    needs: use-build
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: dist

      - name: Upload via FTP
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          server: ftp.bharatsingh.dev
          host: ${{ secrets.SERVER }}
          user: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          localDir: dist
          remoteDir: html